#!/bin/bash


#Porównanie zawartości zadanego katalogu z listą plików (nazwa katalogu i pliku z listą
#zadawana w argumentach skryptu). Należy wygenerować listę plików brakujących w
#katalogu i takich, które nie są na liście


echo "Skrypt 11"	
if [ ! $# -eq 2 ] 	
then
	echo "Brak argumentów"	#wypisujemy komunikat
	exit 1
fi
	
if [[ -d $1 ]] && [[ -e $2 ]]  			
then
	for file in `cat $2`
	do	
		if [[ ! -e $1/$file ]];then
			echo "Plik $file nie istnieje w katalogu"
		fi
	done

	for file1 in `ls $1`
	do	
		isFound=false
		for file2 in `cat $2`
		do 
			if [[ $file1 = $file2 ]]
			then
				isFound=true				
			fi
		done
		if ! $isFound
		then
			echo "Plik $file1 nie wystepuje na liscie"
		fi
	done		
fi



